'use client';

import React, { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { Sparkles, ArrowRight, Layers, Smartphone, Code } from 'lucide-react';
import { RenderNode } from './RenderNode';
import { getHubPosts } from '@/app/actions';
import Link from 'next/link';

export function CommunityShowcase() {
    const [posts, setPosts] = useState<any[]>([]);

    useEffect(() => {
        getHubPosts().then(setPosts).catch(console.error);
    }, []);

    // Filter to show only the best "Golden Samples" if available, or just the first few
    const displayPosts = posts.length > 0 ? posts.slice(0, 3) : [];

    return (
        <section className="py-24 relative bg-black/40 backdrop-blur-3xl border-t border-white/5">

            <div className="max-w-7xl mx-auto px-6">
                {/* Section Header */}
                <div className="text-center mb-16">
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 border border-primary/20 text-primary text-xs font-semibold uppercase tracking-wider mb-4"
                    >
                        <Sparkles className="w-3 h-3" />
                        Community Hub
                    </motion.div>
                    <motion.h2
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        transition={{ delay: 0.1 }}
                        className="text-3xl md:text-5xl font-bold bg-clip-text text-transparent bg-gradient-to-b from-white to-white/60 mb-4"
                    >
                        Built by the Community
                    </motion.h2>
                    <motion.p
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        transition={{ delay: 0.2 }}
                        className="text-muted-foreground max-w-2xl mx-auto text-lg"
                    >
                        Explore UI designs generated by other creators. Use them as a starting point for your next project.
                    </motion.p>
                </div>

                {/* Post Grid */}
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mb-16">
                    {displayPosts.length > 0 ? (
                        displayPosts.map((post, i) => (
                            <motion.div
                                key={post.id}
                                initial={{ opacity: 0, y: 20 }}
                                whileInView={{ opacity: 1, y: 0 }}
                                viewport={{ once: true }}
                                transition={{ delay: i * 0.1 }}
                                className="group relative rounded-2xl bg-zinc-900/50 border border-white/5 hover:border-primary/20 overflow-hidden transition-all duration-300 hover:shadow-2xl hover:shadow-primary/5 hover:-translate-y-1"
                            >
                                {/* Preview Window */}
                                <div className="h-64 overflow-hidden bg-background/50 relative">
                                    <div className="absolute inset-0 flex items-center justify-center p-4 transform scale-75 group-hover:scale-90 transition-transform duration-500 origin-top">
                                        <div className="w-full h-full pointer-events-none select-none shadow-2xl rounded-xl overflow-hidden bg-background border">
                                            {/* Use RenderNode to actually render the DSL preview */}
                                            {/* We wrap it in a container that scales content */}
                                            <div className="origin-top-left transform scale-[0.6] min-w-[166%] min-h-[166%]">
                                                <RenderNode node={post.dsl} />
                                            </div>
                                        </div>
                                    </div>
                                    {/* Overlay Gradient */}
                                    <div className="absolute inset-x-0 bottom-0 h-32 bg-gradient-to-t from-zinc-900 via-zinc-900/80 to-transparent" />
                                </div>

                                {/* Card Content */}
                                <div className="p-6 relative">
                                    <div className="flex items-center gap-3 mb-3">
                                        <div className="w-8 h-8 rounded-full bg-gradient-to-br from-primary/20 to-purple-500/20 flex items-center justify-center text-xs font-bold text-primary">
                                            {post.user?.handle?.[0]?.toUpperCase() || 'U'}
                                        </div>
                                        <div>
                                            <div className="text-sm font-medium text-white group-hover:text-primary transition-colors">{post.user?.handle || 'Anonymous'}</div>
                                            <div className="text-xs text-muted-foreground">Generated {post.style} style</div>
                                        </div>
                                    </div>
                                    <p className="text-sm text-zinc-400 line-clamp-2 mb-4 font-medium">
                                        "{post.prompt}"
                                    </p>

                                    <div className="flex items-center justify-between pt-4 border-t border-white/5">
                                        <div className="flex gap-4 text-xs text-zinc-500">
                                            <span className="flex items-center gap-1"><Layers className="w-3 h-3" /> React</span>
                                            <span className="flex items-center gap-1"><Smartphone className="w-3 h-3" /> Responsive</span>
                                        </div>
                                        {/* Since this is a static showcase on the landing page, we just link to the main app */}
                                        <Link href="/ai-ui-generator" className="text-xs font-semibold text-primary hover:text-primary/80 flex items-center gap-1">
                                            Remix <ArrowRight className="w-3 h-3" />
                                        </Link>
                                    </div>
                                </div>
                            </motion.div>
                        ))
                    ) : (
                        // Fallback Empty State / Skeleton
                        Array.from({ length: 3 }).map((_, i) => (
                            <motion.div
                                key={i}
                                initial={{ opacity: 0 }}
                                whileInView={{ opacity: 1 }}
                                className="h-96 rounded-2xl bg-zinc-900/30 border border-white/5 animate-pulse"
                            />
                        ))
                    )}
                </div>

                {/* Call to Action */}
                <div className="text-center">
                    <Link href="/ai-ui-generator">
                        <motion.button
                            whileHover={{ scale: 1.05 }}
                            whileTap={{ scale: 0.95 }}
                            className="px-8 py-4 rounded-full bg-gradient-to-r from-primary to-purple-600 text-white font-bold text-lg shadow-xl shadow-primary/20 hover:shadow-primary/40 transition-all flex items-center gap-2 mx-auto"
                        >
                            <Code className="w-5 h-5" />
                            Start Generating Now
                        </motion.button>
                    </Link>
                </div>

            </div>
        </section>
    );
}
